'use client';

import { Bell, Check, Command, Info, Sparkles, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { SiteLayout } from '@/components/layout';
import { AnswerOption, CountdownOverlay, LeaderboardItem, LiveStatus, PlayerJoinCard, QuestionProgress, QuizTimer, RoomCode, ScoreDisplay, WinnerPodium } from '@/components/quiz';
import { SoundSettings } from '@/components/sound-settings';
import { ThemeToggle } from '@/components/theme-toggle';
import { Accordion, AchievementCard, Alert, AvatarGroup, BottomSheet, Button, CategoryCard, Checkbox, CompetitionCard, DataTable, DatePicker, Dialog, EmptyState, ErrorState, GameCard, Input, LoadingOverlay, MultiSelect, NumberInput, OtpInput, Pagination, PasswordInput, PlayerCard, Popover, RadioGroup, RewardCard, SearchInput, Select, Separator, Skeleton, Slider, StatisticCard, Stepper, SuccessState, Switch, Tabs, Textarea, TimePicker, Timeline, Tooltip } from '@/components/ui';
import { players } from '@/mocks';

const swatches = ['background', 'foreground', 'card', 'primary', 'secondary', 'accent', 'success', 'danger', 'warning', 'info', 'gold', 'quiz-option-a', 'quiz-option-b', 'quiz-option-c', 'quiz-option-d'];

export default function DesignSystemPage() {
  const [dialog, setDialog] = useState(false); const [sheet, setSheet] = useState(false); const [enabled, setEnabled] = useState(true);
  return <SiteLayout><div className="design-page"><div className="container"><header className="design-header"><div><span className="eyebrow"><Sparkles />مرجع داخلي</span><h1>نظام تصميم تحدّي</h1><p>الهوية البصرية والمكوّنات والحالات التي تبني جميع واجهات المنصة.</p></div><ThemeToggle /></header>
  <DesignSection title="الألوان الدلالية" description="تتبدل القيم تلقائيًا مع الوضعين الداكن والفاتح."><div className="swatch-grid">{swatches.map((name) => <div className="swatch" key={name}><span style={{ background: `var(--${name})` }} /><code>--{name}</code></div>)}</div></DesignSection>
  <DesignSection title="الخط والنصوص"><div className="type-scale"><h1>عنوان عرض كبير</h1><h2>عنوان قسم رئيسي</h2><h3>عنوان بطاقة</h3><p>نص عربي واضح ومريح للقراءة، مع دعم English و2026 دون اضطراب الاتجاه.</p><small>نص مساعد للمعلومات الثانوية</small></div></DesignSection>
  <DesignSection title="الأزرار"><div className="component-row">{(['primary','secondary','outline','ghost','destructive','success','gold','link'] as const).map((variant) => <Button key={variant} variant={variant}>{variant === 'destructive' && <Trash2 />}{variant}</Button>)}<Button loading>جارٍ الحفظ</Button><Button disabled>معطّل</Button><Button size="icon" aria-label="الإشعارات"><Bell /></Button><Button fullWidth>زر بعرض كامل</Button></div></DesignSection>
  <DesignSection title="الحقول"><div className="form-grid"><Input label="الاسم" placeholder="اكتب اسمك" description="سيظهر للاعبين" /><Input label="البريد" defaultValue="player@example.com" success="العنوان متاح" /><Input label="رمز الغرفة" error="الرمز غير صحيح" /><PasswordInput label="كلمة المرور" defaultValue="12345678" /><SearchInput label="البحث" placeholder="ابحث في الأسئلة" /><NumberInput label="عدد الأسئلة" defaultValue={10} /><Select label="الفئة"><option>ثقافة عامة</option><option>علوم</option></Select><MultiSelect label="الفئات" options={['تاريخ','علوم','رياضة']} /><Textarea label="وصف المسابقة" /><DatePicker label="التاريخ" /><TimePicker label="الوقت" /><Slider label="مدة السؤال" defaultValue="60" /><RadioGroup label="الصعوبة" name="difficulty" options={['سهل','متوسط','صعب']} /><div><Checkbox label="إظهار النتائج" defaultChecked /><Switch label="السماح للضيوف" checked={enabled} onChange={setEnabled} /></div><OtpInput /></div></DesignSection>
  <DesignSection title="البطاقات"><div className="card-grid four"><GameCard title="دقيقة ذكاء" description="جولة سريعة" /><CompetitionCard title="كأس المعرفة" description="٢٠ سؤالًا" meta="٢٤٨ لاعبًا" /><CategoryCard title="التاريخ" description="١٢٨ سؤالًا" icon="🏺" /><PlayerCard title="سارة" description="المركز الأول" meta="٩٬٨٤٠" /><AchievementCard title="سلسلة ذهبية" description="١٠ إجابات صحيحة" /><RewardCard title="وسام البطل" description="مكافأة موسمية" /><StatisticCard title="إجابات صحيحة" meta="٨٧٪" description="+١٢٪ هذا الأسبوع" /></div></DesignSection>
  <DesignSection title="النوافذ والعناصر العائمة"><div className="component-row"><Button onClick={() => setDialog(true)}>فتح Dialog</Button><Button variant="outline" onClick={() => setSheet(true)}>فتح Bottom Sheet</Button><Popover trigger="Popover"><p>معلومة سريعة داخل العنصر العائم.</p></Popover><Tooltip label="اختصار لوحة المفاتيح"><Button variant="ghost" size="icon" aria-label="الأوامر"><Command /></Button></Tooltip></div><Dialog open={dialog} onOpenChange={setDialog} title="إنشاء مسابقة" description="هذه نافذة تجريبية مع حجز للتركيز."><Input label="اسم المسابقة" /><Button fullWidth onClick={() => setDialog(false)}>حفظ</Button></Dialog><BottomSheet open={sheet} onOpenChange={setSheet} title="خيارات الجوال"><p>يتحول هذا العنصر إلى لوحة سفلية ملائمة للمس.</p><Button fullWidth onClick={() => setSheet(false)}>تم</Button></BottomSheet></DesignSection>
  <DesignSection title="الرسائل والحالات"><div className="state-grid"><Alert variant="info"><Info />رسالة معلومات</Alert><Alert variant="success"><Check />تم الحفظ بنجاح</Alert><Alert variant="warning">اقترب وقت النهاية</Alert><Alert variant="danger">تعذر الاتصال</Alert><LoadingOverlay /><EmptyState title="لا توجد مسابقات" /><ErrorState /><SuccessState /></div><div className="skeleton-stack"><Skeleton /><Skeleton /><Skeleton /></div></DesignSection>
  <DesignSection title="التنقل والبيانات"><Tabs tabs={['نظرة عامة','اللاعبون','الأسئلة']} /><Stepper steps={['البيانات','الأسئلة','المراجعة']} current={1} /><DataTable headers={['اللاعب','النقاط','الحالة']} rows={players.slice(0,3).map((p) => [p.name,p.score,<LiveStatus key={p.id} status={p.online ? 'live':'offline'} />])} /><Pagination /><Separator /><Accordion items={[{ title:'كيف أضيف مكوّنًا؟', content:'ابدأ بالرموز الدلالية، ثم أضف الحالات والوصولية والاختبار.' }]} /><Timeline items={[{ title:'بدأت الجولة', time:'08:00' },{ title:'ظهر السؤال الرابع', time:'08:04' }]} /><AvatarGroup values={players.slice(0,4).map((p) => p.initials)} /></DesignSection>
  <DesignSection title="مكوّنات المسابقات"><div className="timer-showcase"><QuizTimer total={20} remaining={15} /><QuizTimer total={20} remaining={8} mode="horizontal" /><QuizTimer total={20} remaining={3} mode="digital" /></div><QuestionProgress current={4} total={10} /><div className="answers-list"><AnswerOption label="A" text="المملكة العربية السعودية" /><AnswerOption label="B" text="الجزائر" state="correct" percentage={64} /><AnswerOption label="C" text="السودان" state="wrong" percentage={11} /><AnswerOption label="D" text="مصر" state="disabled" /></div><div className="showcase-split"><RoomCode code="582914" /><ScoreDisplay score={4240} earned={1000} multiplier={1.5} streak={4} /></div>{players.slice(0,3).map((p) => <LeaderboardItem key={p.id} {...p} />)}<PlayerJoinCard {...players[0]} hostTools /><WinnerPodium winners={players.slice(0,3)} confetti={false} /><div className="countdown-preview"><CountdownOverlay value="3" disableMotion /></div></DesignSection>
  <DesignSection title="الصوت والحركة"><SoundSettings /><p className="muted">جميع الحركات تحترم إعداد تقليل الحركة في النظام، ويمكن تعطيلها على مستوى المكوّن.</p></DesignSection>
  </div></div></SiteLayout>;
}

function DesignSection({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="design-section"><header><h2>{title}</h2>{description && <p>{description}</p>}</header><div className="design-canvas">{children}</div></section>; }
